'use strict';

const fs = require('fs');
const path = require('path');

const DEFAULT_URL = 'http://localhost:3000/api';

let apiBaseUrl = process.env.API_BASE_URL;

if (!apiBaseUrl) {
  console.warn(
    '[generate-config] WARNING: API_BASE_URL environment variable is not set. ' +
    `Defaulting to "${DEFAULT_URL}". ` +
    'Set API_BASE_URL before running this script for production builds.'
  );
  apiBaseUrl = DEFAULT_URL;
}

const outputDir = path.join(__dirname, '..', 'js');
const outputFile = path.join(outputDir, 'config.js');

fs.mkdirSync(outputDir, { recursive: true });

const content =
  `// AUTO-GENERATED FILE — do not edit directly. Generated by scripts/generate-config.js\n` +
  `window.API_BASE_URL = "${apiBaseUrl}";\n`;

fs.writeFileSync(outputFile, content, 'utf8');

console.log(`[generate-config] Written: ${outputFile}`);
console.log(`[generate-config] API_BASE_URL = ${apiBaseUrl}`);
